quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:data/db.sqlite
quarkus.hibernate-orm.database.generation=update

%sqlite-init.quarkus.hibernate-orm.database.generation=drop-and-create
