name: Docker build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-native:
    strategy:
      matrix:
        arch:
          - x86-64-v2
          - x86-64-v3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image (${{ matrix.arch }})
        run: |
          docker build \
            --build-arg MARCH=${{ matrix.arch }} \
            -t ${{ github.repository }}:${{ matrix.arch }} .
